## Backend public endpoint
# pattern: http://<proxy>/status/*
# In example this is serves the infoPanel data, and the status endpoints that don't require user auth
apiVersion: oathkeeper.ory.sh/v1alpha1
kind: Rule
metadata:
  name: public-backend-endpoints
spec:
  upstream:
    # DEV_NAMESPACE is filled in by start-dev-env.sh
    url: http://<% .Name %>.{{ DEV_NAMESPACE }}
    stripPath: /{{ DEV_NAMESPACE }}
    preserveHost: true
  match:
    url: http://{{ DEV_NAMESPACE }}.dev.<% index .Params `stagingHostRoot` %>/<(status|webhook)\/.*>
---
## Backend User-restricted endpoint
# pattern: http://<proxy>/<not `status`/`.ory/kratos`>, everything else should be authenticated
# In example this is serves the /userInfo endpoint returning the user-session's info (user_id / email)
# Note the authenticators is `cookie_session`,
# oathkeeper will verify the validity of session then pass along user-id/email in the Request Header
# these can be configured via infra's `oathkeeper-values.yml`
apiVersion: oathkeeper.ory.sh/v1alpha1
kind: Rule
metadata:
  name: authenticated-backend-endpoints
spec:
  upstream:
    preserveHost: true
    url: http://<% .Name %>.{{ DEV_NAMESPACE }}
    stripPath: /{{ DEV_NAMESPACE }}
  match:
    url: http://{{ DEV_NAMESPACE }}.dev.<% index .Params `stagingHostRoot` %>/<(?!(status|webhook|\.ory\/kratos)).*>
  authenticators:
    - handler: cookie_session
      config:
        check_session_url: http://kratos-development-public.user-auth/sessions/whoami
  mutators:
    - handler: id_token
      config:
        issuer_url: https://dev.<% index .Params `stagingHostRoot` %>
    - handler: header

