apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

patchesStrategicMerge:
- deployment.yml
<%if eq (index .Params `userAuth`) "yes" %>- auth.yml
<% end %>

resources:
- ../../base
- ingress.yml
- external-secret.yml

configMapGenerator:
- name: <% .Name %>-config
  behavior: merge
  literals:
    - ENVIRONMENT=staging
